version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle23c
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=tien22012003
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
    driver: local