version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_server_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tien22012003 # <-- Thay đổi mật khẩu của bạn ở đây
      POSTGRES_DB: kiosk_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: