spring.application.name=securityService
server.servlet.context-path=/security/v1
server.port=8010
server.address=0.0.0.0

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/app-prod

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/app-prod/protocol/openid-connect/certs
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=master
keycloak.admin.username=admin
keycloak.admin.password=tien22012003
keycloak.admin.client-id=admin-cli

keycloak.target.realm=app-prod

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/security_pdb
spring.datasource.username=SECURITY_DB
spring.datasource.password=tien22012003
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true