spring.application.name=securityService
server.servlet.context-path=/security/v1
# S?A L?I: ??i spring.port thành server.port
server.port=8010
server.address=0.0.0.0

# ???ng d?n endpoint l?y public key ?? verify token t? Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/app-prod

# ?Ã HOÀN THÀNH: ?i?m ki?m tra tr?c ti?p (JWK Set URI) t? Keycloak
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/app-prod/protocol/openid-connect/certs
# C?u hình server
keycloak.admin.server-url=http://localhost:8080
keycloak.admin.realm=master
keycloak.admin.username=admin
keycloak.admin.password=tien22012003
keycloak.admin.client-id=admin-cli

# Realm m?c tiêu n?i b?n mu?n t?o User m?i cho ?ng d?ng
keycloak.target.realm=app-prod

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/security_pdb
spring.datasource.username=SECURITY_DB
spring.datasource.password=tien22012003
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true